# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-WWW-Mechanize-CGI
version:      0.1
version_from: lib/Test/WWW/Mechanize/CGI.pm
installdirs:  site
requires:
    Test::More:                    0
    Test::WWW::Mechanize:          0
    WWW::Mechanize::CGI:           0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
